"""Add new column

Revision ID: 09d833113007
Revises: 
Create Date: 2025-10-21 06:01:10.208344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d833113007'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_balance', sa.Numeric(precision=18, scale=4), nullable=False))
        batch_op.create_unique_constraint("uq_portfolios_user_id", ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_constraint("uq_portfolios_user_id", type_='unique')
        batch_op.drop_column('cash_balance')

    # ### end Alembic commands ###